blindozer_config = {
    blindozer_health = nil,
    blindozer_index = 0,
    blindozer_position = 0,
    blindozer_angles = 0,
    blindozer_keysl = nil,
}

blindozer_menu = {
    [1] = {
    name = "Собери сытный блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Sitniy_blin.png",
    model = "",
}, 
    [2] = {
    name = "Собери сладкий блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Sladkiy_blin.png",
    model = "",
},
    [3] = {
    name = "Просто блин",
    icon  = "materials/metrostroi_3demc/vending_machine/GUI/Prostoy_blin.png",
    massa = "100г", 
    colories = "208 ККал", 
    belki = "5г", 
    jiri = "3г", 
    yglevodies = "34",  
    sisimasisti = '45', 
    yglevodi = "36г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - Просто блин",
    price = "100",
    model = "blin4",
},
    [4] = {
    name = "Сырный блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Sirniy_blin.png",
    massa = "145г",
    colories = "292 ККал",
    belki = "12г",
    jiri = "11г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр",
    price = "140",
    model = "blin3",
},
    [5] = {
    name = "Голандский блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Golandskiy_blin.png",
    massa = "150г",
    colories = "300 ККал",
    belki = "12г",
    jiri = "12г",
    yglevodi = "34г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - ветчина, лук фри,\nгорчичный соус",
    model = "blin3",
    price = "140",
},
    [6] = {
    name = "Буженина и сыр блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Byjenina_i_sir_blin.png",
    massa = "145г",
    colories = "263 ККал",
    belki = "11г",
    jiri = "8г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, буженина",
    model = "blin3",
    price = "140",
},
    [7] = {
    name = "Богатырь блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Bogatir_blin.png",
    massa = "150г",
    colories = "314 ККал",
    belki = "12г",
    jiri = "8г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, буженина огурцы соленые",
    model = "blin3",
    price = "160",
},
    [8] = {
    name = "Ветчина и сыр блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Vetchina_i_sir_blin.png",
    massa = "145г",
    colories = "263 ККал",
    belki = "10г",
    jiri = "9г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, ветчина",
    model = "blin3",
    price = "140",
},
    [9] = {
    name = "Овощной блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Ovosnoy_blin.png",
    massa = "142г",
    colories = "232 ККал",
    belki = "5г",
    jiri = "7г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - помидоры, огурцы соленые,\nсоусы на выбор",
    model = "blin3",
    price = "140",
},
    [10] = {
    name = "Куриный блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Kuriniy_blin.png",
    massa = "145г",
    colories = "334 ККал",
    belki = "17г",
    jiri = "13г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - грудка куриная помидоры,\nсыр, соусы на выбор",
    model = "blin3",
    price = "160",
},
    [11] = {
    name = "Маргарита блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Margarita_blin.png",
    massa = "145г",
    colories = "284 ККал",
    belki = "8г",
    jiri = "7г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - помидоры, сыр,\nсоусы на выбор",
    model = "blin3",
    price = "140",
},
    [12] = {
    name = "Пикник блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Piknik_blin.png",
    massa = "150г",
    colories = "282 ККал",
    belki = "9г",
    jiri = "12г",
    yglevodi = "32г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - ветчина, сыр, огурцы солёные,\nпомидоры",
    model = "blin3",
    price = "160",
},
    [13] = {
    name = "Яблочный блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Yablochniy_blin.png",
    massa = "145г",
    colories = "204 ККал",
    belki = "5г",
    jiri = "3г",
    yglevodi = "37г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - яблочный джем",
    model = "blin1",
    price = "140",
},
    [14] = {
    name = "Вишневый блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Vishneviy_blin.png",
    massa = "145г",
    colories = "224 ККал",
    belki = "5г",
    jiri = "3г",
    yglevodi = "42г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - вишневый джем",
    model = "blin1",
    price = "140",
},
    [15] = {
    name = "Абрикосовый блин",
    icon = "materials/metrostroi_3demc/vending_machine/GUI/Abricosoviy_blin.png",
    massa = "145г",
    colories = "244 ККал",
    belki = "5г",
    jiri = "3г",
    yglevodi = "47г",
    sostav = "Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - абрикосовый джем",
    model = "blin2",
    price = "140",
},
}

--[MADE IN RUSSIAN]--
--[MADE COPY FYURI4]--
--[MADE COPY 3DEMC]--
--[Copyright 2024 BLINDOZER. Все права защищены. ООО "Сити Венд Кафе"]--
