bler_cfg = {
    bler_heth = 500,
    bler_server_localization = 'ru',
    bler_add_mo_dobavka = {1,2,3,4,5,6,7},
    bler_add_mo_doping = {1,2,4,5},
    bler_add_s_dobavka = {8,9,10},
    bler_add_s_doping = {3},
    bler_add_ep_doping = {1,2,4,5},
}
--[ bler_heth* - Максимальное кол-во жизни у 'автомата' изначально | The maximum number of lives of the 'automaton' is initially ]--

--[                 dobavka                      ]--
--1           Буженина | Pork ham                 --
--2            Ветчина | Ham                      --
--3            Индейка | Turkey                   --
--4 Малосольные огурцы | Lightly salted cucumbers --
--5        Твердый сыр | Hard cheese              --
--6            Лук фри | Onion fries              --
--7   Протертые томаты | Puree tomatoes           --
--8      Яблочный джем | Apple jam                --
--9   Абрикосовый джем | Apricot jam              --
--10     Вишневый джем | Cherry jam               --

--[                 doping                       ]--
--1             Кетчуп | Ketchup                  --
--2             Моенез | Moenes                   --
--3            Сметана | Sour cream               --
--4 Кисло-сладкий соус | Sweet and sour sauce     --
--5            Горчица | Mustard                  --

--[            СТРУКТУРА меню блиндозера | Blindozer menu STRUCTURE             ]--
--[ Не рекомендуется что-либо менять | It is not recommended to change anything ]--

bler_menu = {

    [1] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Sitniy_blin.png',
        Name = 'Собери сытный блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль. Начинка - Просто\nблин, буженина, ветчина, индейка, маринованные\nтвердый сыр, лук фри, протерые томаты.',
        Composition1 = 'Соусы - кетчуп, горчица, кислосладкий соус, сметана.',
        Weight = 100,
        Calories = 208,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 34,
        Model = 'blin3',
        Time = 0,
        Price = 100,
    },
    
    [2] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Sladkiy_blin.png',
        Name = 'Собери сладкий блин',
        Composition = '',
        Weight = 100,
        Calories = 208,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 34,
        Model = 'blin3',
        Time = 0,
        Price = 100,
    },
        
    [3] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Prostoy_blin.png',
        Name = 'Просто блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - Просто блин',
        Weight = 100,
        Calories = 208,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 36,
        Model = 'blin4',
        Time = 0,
        Price = 100,
    },
        
    [4] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Sirniy_blin.png',
        Name = 'Сырный блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр',
        Weight = 145,
        Calories = 292,
        Squirrels = 12,
        Fats = 11,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [5] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Golandskiy_blin.png',
        Name = 'Голандский блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - ветчина, лук фри,\nгорчичный соус',
        Weight = 150,
        Calories = 300,
        Squirrels = 12,
        Fats = 12,
        Carbohydrates = 34,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [6] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Byjenina_i_sir_blin.png',
        Name = 'Буженина и сыр блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, буженина',
        Weight = 145,
        Calories = 263,
        Squirrels = 11,
        Fats = 8,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [7] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Bogatir_blin.png',
        Name = 'Богатырь блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, буженина огурцы соленые',
        Weight = 150,
        Calories = 314,
        Squirrels = 12,
        Fats = 8,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 160,
    },
        
    [8] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Vetchina_i_sir_blin.png',
        Name = 'Ветчина и сыр блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - cыр, ветчина',
        Weight = 145,
        Calories = 263,
        Squirrels = 10,
        Fats = 9,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [9] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Ovosnoy_blin.png',
        Name = 'Овощной блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - помидоры, огурцы соленые,\nсоусы на выбор',
        Weight = 142,
        Calories = 232,
        Squirrels = 5,
        Fats = 7,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [10] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Kuriniy_blin.png',
        Name = 'Куриный блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - грудка куриная помидоры,\nсыр, соусы на выбор',
        Weight = 145,
        Calories = 334,
        Squirrels = 17,
        Fats = 13,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 160,
    },
        
    [11] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Margarita_blin.png',
        Name = 'Маргарита блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - помидоры, сыр,\nсоусы на выбор',
        Weight = 145,
        Calories = 284,
        Squirrels = 8,
        Fats = 7,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 140,
    },
        
    [12] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Piknik_blin.png',
        Name = 'Пикник блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - ветчина, сыр, огурцы солёные,\nпомидоры',
        Weight = 150,
        Calories = 282,
        Squirrels = 9,
        Fats = 12,
        Carbohydrates = 32,
        Model = 'blin3',
        Time = 0,
        Price = 160,
    },
        
    [13] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Yablochniy_blin.png',
        Name = 'Яблочный блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - яблочный джем',
        Weight = 145,
        Calories = 204,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 37,
        Model = 'blin1',
        Time = 0,
        Price = 140,
    },
        
    [14] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Vishneviy_blin.png',
        Name = 'Вишневый блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - вишневый джем',
        Weight = 145,
        Calories = 224,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 42,
        Model = 'blin1',
        Time = 0,
        Price = 140,
    },
        
    [15] = {
        Icon = 'materials/metrostroi_3demc/vending_machine/GUI/Abricosoviy_blin.png',
        Name = 'Абрикосовый блин',
        Composition = '                Тесто - мука пшеничная, молоко, яйца,\nмасло растительное, сахар, соль.\nНачинка - абрикосовый джем',
        Weight = 145,
        Calories = 244,
        Squirrels = 5,
        Fats = 3,
        Carbohydrates = 47,
        Model = 'blin2',
        Time = 0,
        Price = 140,
    },
}

--[        СТРУКТУРА добавки Блиндозера | Blindozer dobavka STRUCTURE           ]--
--[ Не рекомендуется что-либо менять | It is not recommended to change anything ]--

bler_dobavka = {
    [1] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_1.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_1_true.png',
        Name = 'Буженина',
        Weight = 100,
        Calories = 328,
        Squirrels = 28,
        Fats = 23,
        Carbohydrates = 0,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [2] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_2.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_2_true.png',
        Name = 'Ветчина',
        Weight = 100,
        Calories = 270,
        Squirrels = 22,
        Fats = 20,
        Carbohydrates = 0,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [3] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_3.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_3_true.png',
        Name = 'Индейка',
        Weight = 100,
        Calories = 135,
        Squirrels = 23,
        Fats = 3,
        Carbohydrates = 0,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [4] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_4.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_4_true.png',
        Name = 'Малосольные огурцы',
        Weight = 100,
        Calories = 10,
        Squirrels = 1,
        Fats = 0,
        Carbohydrates = 2,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [5] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_5.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_5_true.png',
        Name = 'Твердый сыр',
        Weight = 100,
        Calories = 402,
        Squirrels = 25,
        Fats = 33,
        Carbohydrates = 0,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [6] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_6.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_6_true.png',
        Name = 'Лук фри',
        Weight = 100,
        Calories = 485,
        Squirrels = 4,
        Fats = 24,
        Carbohydrates = 63,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [7] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_7.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_7_true.png',
        Name = 'Протертые томаты',
        Weight = 100,
        Calories = 18,
        Squirrels = 1,
        Fats = 0,
        Carbohydrates = 3,
        Time = 0,
        Price = 35,
        Сondition = false,
    },
    [8] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_8.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_8_true.png',
        Name = 'Яблочный джем',
        Weight = 100,
        Calories = 241,
        Squirrels = 0,
        Fats = 0,
        Carbohydrates = 60,
        Time = 0,
        Price = 20,
        Сondition = false,
    },
    [9] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_9.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_9_true.png',
        Name = 'Абрикосовый джем',
        Weight = 100,
        Calories = 241,
        Squirrels = 0,
        Fats = 0,
        Carbohydrates = 60,
        Time = 0,
        Price = 20,
        Сondition = false,
    },
    [10] = {
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_2_0.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping1_2_0_true.png',
        Name = 'Вишневый джем',
        Weight = 100,
        Calories = 241,
        Squirrels = 0,
        Fats = 0,
        Carbohydrates = 60,
        Time = 0,
        Price = 20,
        Сondition = false,
    },
    
}

--[         СТРУКТУРА допингов Блиндозера | Blindozer doping STRUCTURE          ]--
--[ Не рекомендуется что-либо менять | It is not recommended to change anything ]--

bler_doping = {
    [1] = {
        Name = 'Кетчуп',
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_1.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_1_true.png',
        Weight = 100,
        Calories = 90,
        Squirrels = 1,
        Fats = 0.1,
        Carbohydrates = 20,
        Price = 20,
        Сondition = false,
    },
    [2] = {
        Name = 'Моенез',
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_2.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_2_true.png',
        Weight = 100,
        Calories = 600,
        Squirrels = 1,
        Fats = 65,
        Carbohydrates = 1,
        Price = 20,
        Сondition = false,
    },
    [3] = {
        Name = 'Сметана',
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_3.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_3_true.png',
        Weight = 100,
        Calories = 200,
        Squirrels = 2,
        Fats = 20,
        Carbohydrates = 3,
        Price = 20,
        Сondition = false,
    },
    [4] = {
        Name = 'Ки-ий соус',
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_4.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_4_true.png',
        Weight = 100,
        Calories = 60,
        Squirrels = 4,
        Fats = 3,
        Carbohydrates = 5,
        Price = 20,
        Сondition = false,
    },
    [5] = {
        Name = 'Горчица',
        Icon_false = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_5.png',
        Icon_true = 'materials/metrostroi_3demc/vending_machine/BLINDOZER_GUI/Doping2_5_true.png',
        Weight = 100,
        Calories = 100,
        Squirrels = 0,
        Fats = 0,
        Carbohydrates = 25,
        Price = 20,
        Сondition = false,
    },
}